// Generated by dzn code from ForeignEndstop.dzn
#include <dzn/runtime.hh>
namespace dzn
{
  struct locator;
  struct runtime;
}
#include <iostream>
#include <vector>
#include <map>
#include "IEndstop.hh"
#ifndef SKEL_FENDSTOP_HH
#define SKEL_FENDSTOP_HH
#include "IEndstop.hh"
namespace skel
{
  struct FEndstop: public dzn::component
    {
      dzn::meta dzn_meta;
      dzn::runtime& dzn_runtime;
      dzn::locator const& dzn_locator;
      ::IEndstop::State* dzn_reply_IEndstop_State;
      std::function<void ()>* dzn_out_p;
      ::IEndstop p;
      FEndstop (dzn::locator const& locator);
      virtual ~FEndstop ();
      protected:
      void p_entering ();
      void p_exiting ();
      private:
      virtual ::IEndstop::State p_getState () = 0;
    };
}
#endif // SKEL_FENDSTOP_HH
// version 2.18.2
