// Generated by dzn code from ForeignTimer.dzn
#include <dzn/runtime.hh>
namespace dzn
{
  struct locator;
  struct runtime;
}
#include <iostream>
#include <vector>
#include <map>
#include "ITimer.hh"
#ifndef SKEL_FTIMER_HH
#define SKEL_FTIMER_HH
#include "ITimer.hh"
namespace skel
{
  struct FTimer: public dzn::component
    {
      dzn::meta dzn_meta;
      dzn::runtime& dzn_runtime;
      dzn::locator const& dzn_locator;
      std::function<void ()>* dzn_out_p;
      ::ITimer p;
      FTimer (dzn::locator const& locator);
      virtual ~FTimer ();
      protected:
      void p_timerElapsed ();
      private:
      virtual void p_setTimer (Delay delayInS) = 0;
      virtual void p_cancelTimer () = 0;
    };
}
#endif // SKEL_FTIMER_HH
// version 2.18.2
