// Generated by dzn code from ForeignTimer.dzn
#include "ForeignTimer.hh"
#include <dzn/locator.hh>
#include <dzn/runtime.hh>
#include <iterator>
#define STRINGIZING(x) #x
#define STR(x) STRINGIZING (x)
#define LOCATION __FILE__ ":" STR (__LINE__)
namespace skel
{
  FTimer::FTimer (dzn::locator const& locator)
  : dzn_meta (  {"FTimer","FTimer",0,  {},  {},  {[this] ()
            {
              p.dzn_check_bindings ();
            }}})
  , dzn_runtime (locator.get<dzn::runtime> ())
  , dzn_locator (locator)
  , p (  {  {"p",&p,this,&dzn_meta},  {"p",0,0,0}},this)
    {
      this->p.in.setTimer = [this] (Delay delayInS)
        {
          this->dzn_out_p = &this->p.in.setTimer.dzn_out_binding;
          this->p_setTimer (delayInS);
        };
      this->p.in.cancelTimer = [this] ()
        {
          this->dzn_out_p = &this->p.in.cancelTimer.dzn_out_binding;
          this->p_cancelTimer ();
        };
    }
  FTimer::~FTimer ()
    {}
  void
  FTimer::p_timerElapsed ()
    {
      this->p.out.timerElapsed ();
    }
}
// version 2.18.2
