// Generated by dzn code from ForeignPositionSensor.dzn
#include <dzn/runtime.hh>
namespace dzn
{
  struct locator;
  struct runtime;
}
#include <iostream>
#include <vector>
#include <map>
#include "IPositionSensor.hh"
#ifndef SKEL_FPOSITIONSENSOR_HH
#define SKEL_FPOSITIONSENSOR_HH
#include "IPositionSensor.hh"
namespace skel
{
  struct FPositionSensor: public dzn::component
    {
      dzn::meta dzn_meta;
      dzn::runtime& dzn_runtime;
      dzn::locator const& dzn_locator;
      std::function<void ()>* dzn_out_p;
      ::IPositionSensor p;
      FPositionSensor (dzn::locator const& locator);
      virtual ~FPositionSensor ();
      protected:
      private:
      virtual void p_getCurrentPosition (Position posInM) = 0;
      virtual void p_getLastEndstopPosition (Position posInM) = 0;
    };
}
#endif // SKEL_FPOSITIONSENSOR_HH
// version 2.18.2
