// Generated by dzn code from ForeignPositionSensor.dzn
#include "ForeignPositionSensor.hh"
#include <dzn/locator.hh>
#include <dzn/runtime.hh>
#include <iterator>
#define STRINGIZING(x) #x
#define STR(x) STRINGIZING (x)
#define LOCATION __FILE__ ":" STR (__LINE__)
namespace skel
{
  FPositionSensor::FPositionSensor (dzn::locator const& locator)
  : dzn_meta (  {"FPositionSensor","FPositionSensor",0,  {},  {},  {[this] ()
            {
              p.dzn_check_bindings ();
            }}})
  , dzn_runtime (locator.get<dzn::runtime> ())
  , dzn_locator (locator)
  , p (  {  {"p",&p,this,&dzn_meta},  {"p",0,0,0}},this)
    {
      this->p.in.getCurrentPosition = [this] (Position posInM)
        {
          this->dzn_out_p = &this->p.in.getCurrentPosition.dzn_out_binding;
          this->p_getCurrentPosition (posInM);
        };
      this->p.in.getLastEndstopPosition = [this] (Position posInM)
        {
          this->dzn_out_p = &this->p.in.getLastEndstopPosition.dzn_out_binding;
          this->p_getLastEndstopPosition (posInM);
        };
    }
  FPositionSensor::~FPositionSensor ()
    {}
}
// version 2.18.2
