// Generated by dzn code from ForeignDestinationSensor.dzn
#include "ForeignDestinationSensor.hh"
#include <dzn/locator.hh>
#include <dzn/runtime.hh>
#include <iterator>
#define STRINGIZING(x) #x
#define STR(x) STRINGIZING (x)
#define LOCATION __FILE__ ":" STR (__LINE__)
namespace skel
{
  FDestinationSensor::FDestinationSensor (dzn::locator const& locator)
  : dzn_meta (  {"FDestinationSensor","FDestinationSensor",0,  {},  {},  {[this] ()
            {
              p.dzn_check_bindings ();
            }}})
  , dzn_runtime (locator.get<dzn::runtime> ())
  , dzn_locator (locator)
  , p (  {  {"p",&p,this,&dzn_meta},  {"p",0,0,0}},this)
    {
      this->p.in.setDestination = [this] (Position posInM)
        {
          this->dzn_out_p = &this->p.in.setDestination.dzn_out_binding;
          this->p_setDestination (posInM);
        };
      this->p.in.cancelDestination = [this] ()
        {
          this->dzn_out_p = &this->p.in.cancelDestination.dzn_out_binding;
          this->p_cancelDestination ();
        };
    }
  FDestinationSensor::~FDestinationSensor ()
    {}
  void
  FDestinationSensor::p_destinationReached ()
    {
      this->p.out.destinationReached ();
    }
}
// version 2.18.2
