// Generated by dzn code from ForeignEndstop.dzn
#include "ForeignEndstop.hh"
#include <dzn/locator.hh>
#include <dzn/runtime.hh>
#include <iterator>
#define STRINGIZING(x) #x
#define STR(x) STRINGIZING (x)
#define LOCATION __FILE__ ":" STR (__LINE__)
namespace skel
{
  FEndstop::FEndstop (dzn::locator const& locator)
  : dzn_meta (  {"FEndstop","FEndstop",0,  {},  {},  {[this] ()
            {
              p.dzn_check_bindings ();
            }}})
  , dzn_runtime (locator.get<dzn::runtime> ())
  , dzn_locator (locator)
  , p (  {  {"p",&p,this,&dzn_meta},  {"p",0,0,0}},this)
    {
      this->p.in.getState = [this] ()
        {
          this->dzn_out_p = &this->p.in.getState.dzn_out_binding;
          this->dzn_reply_IEndstop_State = &this->p.in.getState.reply;
          return this->p_getState ();
        };
    }
  FEndstop::~FEndstop ()
    {}
  void
  FEndstop::p_entering ()
    {
      this->p.out.entering ();
    }
  void
  FEndstop::p_exiting ()
    {
      this->p.out.exiting ();
    }
}
// version 2.18.2
