// Generated by dzn code from ForeignMotor.dzn
#include <dzn/runtime.hh>
namespace dzn
{
  struct locator;
  struct runtime;
}
#include <iostream>
#include <vector>
#include <map>
#include "IMotor.hh"
#ifndef SKEL_FMOTOR_HH
#define SKEL_FMOTOR_HH
#include "IMotor.hh"
namespace skel
{
  struct FMotor: public dzn::component
    {
      dzn::meta dzn_meta;
      dzn::runtime& dzn_runtime;
      dzn::locator const& dzn_locator;
      std::function<void ()>* dzn_out_p;
      ::IMotor p;
      FMotor (dzn::locator const& locator);
      virtual ~FMotor ();
      protected:
      private:
      virtual void p_moveUpFast () = 0;
      virtual void p_moveUpSlow () = 0;
      virtual void p_moveDownFast () = 0;
      virtual void p_moveDownSlow () = 0;
      virtual void p_stop () = 0;
    };
}
#endif // SKEL_FMOTOR_HH
// version 2.18.2
