// Generated by dzn code from ForeignLog.dzn
#include <dzn/runtime.hh>
namespace dzn
{
  struct locator;
  struct runtime;
}
#include <iostream>
#include <vector>
#include <map>
#include "ILog.hh"
#ifndef SKEL_FLOG_HH
#define SKEL_FLOG_HH
#include "ILog.hh"
namespace skel
{
  struct FLog: public dzn::component
    {
      dzn::meta dzn_meta;
      dzn::runtime& dzn_runtime;
      dzn::locator const& dzn_locator;
      std::function<void ()>* dzn_out_p;
      ::ILog p;
      FLog (dzn::locator const& locator);
      virtual ~FLog ();
      protected:
      private:
      virtual void p_logMsg (std::string msg) = 0;
    };
}
#endif // SKEL_FLOG_HH
// version 2.18.2
