// Generated by dzn code from ForeignLog.dzn
#include "ForeignLog.hh"
#include <dzn/locator.hh>
#include <dzn/runtime.hh>
#include <iterator>
#define STRINGIZING(x) #x
#define STR(x) STRINGIZING (x)
#define LOCATION __FILE__ ":" STR (__LINE__)
namespace skel
{
  FLog::FLog (dzn::locator const& locator)
  : dzn_meta (  {"FLog","FLog",0,  {},  {},  {[this] ()
            {
              p.dzn_check_bindings ();
            }}})
  , dzn_runtime (locator.get<dzn::runtime> ())
  , dzn_locator (locator)
  , p (  {  {"p",&p,this,&dzn_meta},  {"p",0,0,0}},this)
    {
      this->p.in.logMsg = [this] (std::string msg)
        {
          this->dzn_out_p = &this->p.in.logMsg.dzn_out_binding;
          this->p_logMsg (msg);
        };
    }
  FLog::~FLog ()
    {}
}
// version 2.18.2
