// Generated by dzn code from IDestinationSensor.dzn
// import Types.dzn;
#include "IDestinationSensor.hh"
#include <dzn/locator.hh>
#include <dzn/runtime.hh>
#include <iterator>
#define STRINGIZING(x) #x
#define STR(x) STRINGIZING (x)
#define LOCATION __FILE__ ":" STR (__LINE__)
IDestinationSensor::IDestinationSensor (dzn::port::meta const& m)
: dzn_meta (m)
, dzn_share_p (true)
, dzn_label ("")
, dzn_state ()
, state (::IDestinationSensor::State::IDLE)
{}
IDestinationSensor::~IDestinationSensor ()= default;
void
IDestinationSensor::dzn_event (char const* event)
{
  if (!dzn_share_p) return;
  dzn_label = event;
}
void
IDestinationSensor::dzn_update_state (dzn::locator const& locator)
{
  if (!dzn_share_p || !dzn_label) return;
  switch (dzn::hash (dzn_label, dzn_state))
    {
      case 3409341603u:
      //0:setDestination
      dzn_state = 4;
      break;
      case 632232382u:
      //1:return
      dzn_state = 0;
      state = IDestinationSensor::State::IDLE;
      break;
      case 4005074u:
      //2:cancelDestination
      dzn_state = 1;
      break;
      case 4140549353u:
      //2:destinationReached
      dzn_state = 0;
      state = IDestinationSensor::State::IDLE;
      break;
      case 632232619u:
      //4:return
      dzn_state = 2;
      state = IDestinationSensor::State::ARMED;
      break;
      default: locator.get<dzn::illegal_handler> ().handle (LOCATION);
    }
}
void
IDestinationSensor::dzn_check_bindings ()
{
  if (!this->in.setDestination) throw dzn::binding_error (this->dzn_meta, "in.setDestination");
  if (!this->in.cancelDestination) throw dzn::binding_error (this->dzn_meta, "in.cancelDestination");
  if (!this->out.destinationReached) throw dzn::binding_error (this->dzn_meta, "out.destinationReached");
}
namespace dzn
{
}
// version 2.18.2
