// Generated by dzn code from IDestinationSensor.dzn
// import Types.dzn;
#include <dzn/runtime.hh>
namespace dzn
{
  struct locator;
  struct runtime;
}
#include <iostream>
#include <vector>
#include <map>
#ifndef IDESTINATIONSENSOR_HH
#define IDESTINATIONSENSOR_HH
struct IDestinationSensor
{
  enum struct State
    {
      IDLE,ARMED
    };
  dzn::port::meta dzn_meta;
  struct
    {
      dzn::in::event<void (Position posInM)> setDestination;
      dzn::in::event<void ()> cancelDestination;
    } in;
  struct
    {
      dzn::out::event<void ()> destinationReached;
    } out;
  bool dzn_share_p;
  char const* dzn_label;
  int dzn_state;
  ::IDestinationSensor::State state;
  IDestinationSensor (dzn::port::meta const& m);
  template <typename Component>
  IDestinationSensor (dzn::port::meta const& m, Component* that)
  : dzn_meta (m)
  , dzn_share_p (true)
  , dzn_label ("")
  , dzn_state ()
  , state (::IDestinationSensor::State::IDLE)
    {
      in.setDestination.set (that, this, "setDestination");
      in.cancelDestination.set (that, this, "cancelDestination");
      out.destinationReached.set (that, this, "destinationReached");
    }
  virtual ~IDestinationSensor ();
  void dzn_event (char const* event);
  void dzn_update_state (dzn::locator const& locator);
  void dzn_check_bindings ();
};
namespace dzn
{
  inline void connect (::IDestinationSensor& provide, ::IDestinationSensor& require)
    {
      provide.out.destinationReached = require.out.destinationReached;
      require.in.setDestination = provide.in.setDestination;
      require.in.cancelDestination = provide.in.cancelDestination;
      provide.dzn_meta.require = require.dzn_meta.require;
      require.dzn_meta.provide = provide.dzn_meta.provide;
      provide.dzn_share_p = require.dzn_share_p = provide.dzn_share_p && require.dzn_share_p;
    }
}
#endif // IDESTINATIONSENSOR_HH
// version 2.18.2
