// Generated by dzn code from IMoveUpDownRelaxed.dzn
#include "IMoveUpDownRelaxed.hh"
#include <dzn/locator.hh>
#include <dzn/runtime.hh>
#include <iterator>
#define STRINGIZING(x) #x
#define STR(x) STRINGIZING (x)
#define LOCATION __FILE__ ":" STR (__LINE__)
IMoveUpDownRelaxed::IMoveUpDownRelaxed (dzn::port::meta const& m)
: dzn_meta (m)
, dzn_share_p (true)
, dzn_label ("")
, dzn_state ()
, state (::IMoveUpDownRelaxed::State::IDLE)
{}
IMoveUpDownRelaxed::~IMoveUpDownRelaxed ()= default;
void
IMoveUpDownRelaxed::dzn_event (char const* event)
{
  if (!dzn_share_p) return;
  dzn_label = event;
}
void
IMoveUpDownRelaxed::dzn_update_state (dzn::locator const& locator)
{
  if (!dzn_share_p || !dzn_label) return;
  switch (dzn::hash (dzn_label, dzn_state))
    {
      case 3709750896u:
      //0:abort
      dzn_state = 1;
      break;
      case 2475689452u:
      //0:moveDown
      dzn_state = 12;
      break;
      case 3747270931u:
      //0:moveUp
      dzn_state = 8;
      break;
      case 632232382u:
      //1:return
      dzn_state = 0;
      state = IMoveUpDownRelaxed::State::IDLE;
      break;
      case 3709751054u:
      //2:abort
      dzn_state = 3;
      break;
      case 2475689610u:
      //2:moveDown
      dzn_state = 8;
      break;
      case 548029951u:
      //2:moveFailed
      dzn_state = 0;
      state = IMoveUpDownRelaxed::State::IDLE;
      break;
      case 2016493930u:
      //2:moveFinished
      dzn_state = 5;
      state = IMoveUpDownRelaxed::State::UP;
      break;
      case 3747271089u:
      //2:moveUp
      dzn_state = 8;
      break;
      case 632232540u:
      //3:return
      dzn_state = 4;
      state = IMoveUpDownRelaxed::State::ABORTING;
      break;
      case 3709751212u:
      //4:abort
      dzn_state = 3;
      break;
      case 2410838042u:
      //4:moveAborted
      dzn_state = 0;
      state = IMoveUpDownRelaxed::State::IDLE;
      break;
      case 2475689768u:
      //4:moveDown
      dzn_state = 3;
      break;
      case 3747271247u:
      //4:moveUp
      dzn_state = 3;
      break;
      case 3709751291u:
      //5:abort
      dzn_state = 7;
      break;
      case 2475689847u:
      //5:moveDown
      dzn_state = 12;
      break;
      case 3747271326u:
      //5:moveUp
      dzn_state = 7;
      break;
      case 632232856u:
      //7:return
      dzn_state = 5;
      state = IMoveUpDownRelaxed::State::UP;
      break;
      case 632232935u:
      //8:return
      dzn_state = 2;
      state = IMoveUpDownRelaxed::State::MOVING_UP;
      break;
      case 3709751607u:
      //9:abort
      dzn_state = 10;
      break;
      case 2475690163u:
      //9:moveDown
      dzn_state = 10;
      break;
      case 3747271642u:
      //9:moveUp
      dzn_state = 8;
      break;
      case 2701711839u:
      //10:return
      dzn_state = 9;
      state = IMoveUpDownRelaxed::State::DOWN;
      break;
      case 1012551055u:
      //11:abort
      dzn_state = 3;
      break;
      case 2305944787u:
      //11:moveDown
      dzn_state = 12;
      break;
      case 344687086u:
      //11:moveFailed
      dzn_state = 0;
      state = IMoveUpDownRelaxed::State::IDLE;
      break;
      case 389224435u:
      //11:moveFinished
      dzn_state = 9;
      state = IMoveUpDownRelaxed::State::DOWN;
      break;
      case 3976633820u:
      //11:moveUp
      dzn_state = 12;
      break;
      case 2701724321u:
      //12:return
      dzn_state = 11;
      state = IMoveUpDownRelaxed::State::MOVING_DOWN;
      break;
      default: locator.get<dzn::illegal_handler> ().handle (LOCATION);
    }
}
void
IMoveUpDownRelaxed::dzn_check_bindings ()
{
  if (!this->in.moveUp) throw dzn::binding_error (this->dzn_meta, "in.moveUp");
  if (!this->in.moveDown) throw dzn::binding_error (this->dzn_meta, "in.moveDown");
  if (!this->in.abort) throw dzn::binding_error (this->dzn_meta, "in.abort");
  if (!this->out.moveFinished) throw dzn::binding_error (this->dzn_meta, "out.moveFinished");
  if (!this->out.moveAborted) throw dzn::binding_error (this->dzn_meta, "out.moveAborted");
  if (!this->out.moveFailed) throw dzn::binding_error (this->dzn_meta, "out.moveFailed");
}
namespace dzn
{
}
// version 2.18.2
