// Generated by dzn code from IMoveUpDown.dzn
#include "IMoveUpDown.hh"
#include <dzn/locator.hh>
#include <dzn/runtime.hh>
#include <iterator>
#define STRINGIZING(x) #x
#define STR(x) STRINGIZING (x)
#define LOCATION __FILE__ ":" STR (__LINE__)
IMoveUpDown::IMoveUpDown (dzn::port::meta const& m)
: dzn_meta (m)
, dzn_share_p (true)
, dzn_label ("")
, dzn_state ()
, state (::IMoveUpDown::State::IDLE)
{}
IMoveUpDown::~IMoveUpDown ()= default;
void
IMoveUpDown::dzn_event (char const* event)
{
  if (!dzn_share_p) return;
  dzn_label = event;
}
void
IMoveUpDown::dzn_update_state (dzn::locator const& locator)
{
  if (!dzn_share_p || !dzn_label) return;
  switch (dzn::hash (dzn_label, dzn_state))
    {
      case 3709750896u:
      //0:abort
      dzn_state = 1;
      break;
      case 2475689452u:
      //0:moveDown
      dzn_state = 9;
      break;
      case 3747270931u:
      //0:moveUp
      dzn_state = 11;
      break;
      case 632232382u:
      //1:return
      dzn_state = 0;
      state = IMoveUpDown::State::IDLE;
      break;
      case 3709751054u:
      //2:abort
      dzn_state = 3;
      break;
      case 548029951u:
      //2:moveFailed
      dzn_state = 0;
      state = IMoveUpDown::State::IDLE;
      break;
      case 2016493930u:
      //2:moveFinished
      dzn_state = 5;
      state = IMoveUpDown::State::DOWN;
      break;
      case 632232540u:
      //3:return
      dzn_state = 4;
      state = IMoveUpDown::State::ABORTING;
      break;
      case 2410838042u:
      //4:moveAborted
      dzn_state = 0;
      state = IMoveUpDown::State::IDLE;
      break;
      case 3709751291u:
      //5:abort
      dzn_state = 7;
      break;
      case 3747271326u:
      //5:moveUp
      dzn_state = 11;
      break;
      case 632232856u:
      //7:return
      dzn_state = 5;
      state = IMoveUpDown::State::DOWN;
      break;
      case 3709751528u:
      //8:abort
      dzn_state = 12;
      break;
      case 2475690084u:
      //8:moveDown
      dzn_state = 9;
      break;
      case 632233014u:
      //9:return
      dzn_state = 2;
      state = IMoveUpDown::State::MOVING_DOWN;
      break;
      case 1012544814u:
      //10:abort
      dzn_state = 3;
      break;
      case 344680845u:
      //10:moveFailed
      dzn_state = 0;
      state = IMoveUpDown::State::IDLE;
      break;
      case 389218194u:
      //10:moveFinished
      dzn_state = 8;
      state = IMoveUpDown::State::UP;
      break;
      case 2701718080u:
      //11:return
      dzn_state = 10;
      state = IMoveUpDown::State::MOVING_UP;
      break;
      case 2701724321u:
      //12:return
      dzn_state = 8;
      state = IMoveUpDown::State::UP;
      break;
      default: locator.get<dzn::illegal_handler> ().handle (LOCATION);
    }
}
void
IMoveUpDown::dzn_check_bindings ()
{
  if (!this->in.moveUp) throw dzn::binding_error (this->dzn_meta, "in.moveUp");
  if (!this->in.moveDown) throw dzn::binding_error (this->dzn_meta, "in.moveDown");
  if (!this->in.abort) throw dzn::binding_error (this->dzn_meta, "in.abort");
  if (!this->out.moveFinished) throw dzn::binding_error (this->dzn_meta, "out.moveFinished");
  if (!this->out.moveAborted) throw dzn::binding_error (this->dzn_meta, "out.moveAborted");
  if (!this->out.moveFailed) throw dzn::binding_error (this->dzn_meta, "out.moveFailed");
}
namespace dzn
{
}
// version 2.18.2
