// Generated by dzn code from IPositionSensor.dzn
// import Types.dzn;
#include <dzn/runtime.hh>
namespace dzn
{
  struct locator;
  struct runtime;
}
#include <iostream>
#include <vector>
#include <map>
#ifndef IPOSITIONSENSOR_HH
#define IPOSITIONSENSOR_HH
struct IPositionSensor
{
  dzn::port::meta dzn_meta;
  struct
    {
      dzn::in::event<void (Position posInM)> getCurrentPosition;
      dzn::in::event<void (Position posInM)> getLastEndstopPosition;
    } in;
  struct
    {
    } out;
  bool dzn_share_p;
  char const* dzn_label;
  int dzn_state;
  IPositionSensor (dzn::port::meta const& m);
  template <typename Component>
  IPositionSensor (dzn::port::meta const& m, Component* that)
  : dzn_meta (m)
  , dzn_share_p (true)
  , dzn_label ("")
  , dzn_state ()
    {
      in.getCurrentPosition.set (that, this, "getCurrentPosition");
      in.getLastEndstopPosition.set (that, this, "getLastEndstopPosition");
    }
  virtual ~IPositionSensor ();
  void dzn_event (char const* event);
  void dzn_update_state (dzn::locator const& locator);
  void dzn_check_bindings ();
};
namespace dzn
{
  inline void connect (::IPositionSensor& provide, ::IPositionSensor& require)
    {
      require.in.getCurrentPosition = provide.in.getCurrentPosition;
      require.in.getLastEndstopPosition = provide.in.getLastEndstopPosition;
      provide.dzn_meta.require = require.dzn_meta.require;
      require.dzn_meta.provide = provide.dzn_meta.provide;
      provide.dzn_share_p = require.dzn_share_p = provide.dzn_share_p && require.dzn_share_p;
    }
}
#endif // IPOSITIONSENSOR_HH
// version 2.18.2
