// Generated by dzn code from MoveUpDownTopArmor.dzn
#include "MoveUpDownTopArmor.hh"
#include <dzn/locator.hh>
#include <dzn/runtime.hh>
#include <iterator>
#define STRINGIZING(x) #x
#define STR(x) STRINGIZING (x)
#define LOCATION __FILE__ ":" STR (__LINE__)
MoveUpDownTopArmor::MoveUpDownTopArmor (dzn::locator const& locator)
: dzn_meta ({"MoveUpDownTopArmor","MoveUpDownTopArmor",0,  {},  {},  {[this] ()
        {
          p.dzn_check_bindings ();
        }, [this] ()
        {
          r.dzn_check_bindings ();
        }, [this] ()
        {
          rLog.dzn_check_bindings ();
        }}})
, dzn_runtime (locator.get<dzn::runtime> ())
, dzn_locator (locator)
, state (::MoveUpDownTopArmor::State::IDLE)
, p ({  {"p",&p,this,&dzn_meta},  {"p",0,0,0}},this)
, r ({  {"r",0,0,0},  {"r",&r,this,&dzn_meta}},this)
, rLog ({  {"rLog",0,0,0},  {"rLog",&rLog,this,&dzn_meta}},this)
{
  this->dzn_meta.require =   {&r.dzn_meta,&rLog.dzn_meta};
  this->dzn_runtime.performs_flush (this) = true;
  this->p.in.moveUp = [this] ()
    {
      this->dzn_out_p = &this->p.in.moveUp.dzn_out_binding;
      this->p_moveUp ();
    };
  this->p.in.moveDown = [this] ()
    {
      this->dzn_out_p = &this->p.in.moveDown.dzn_out_binding;
      this->p_moveDown ();
    };
  this->p.in.abort = [this] ()
    {
      this->dzn_out_p = &this->p.in.abort.dzn_out_binding;
      this->p_abort ();
    };
  this->r.out.moveFinished = [this] ()
    {
      this->r_moveFinished ();
    };
  this->r.out.moveAborted = [this] ()
    {
      this->r_moveAborted ();
    };
  this->r.out.moveFailed = [this] ()
    {
      this->r_moveFailed ();
    };
}
void
MoveUpDownTopArmor::p_moveUp ()
{
  if (this->state == ::MoveUpDownTopArmor::State::IDLE)
    {
      this->r.in.moveUp ();
      this->state = ::MoveUpDownTopArmor::State::MOVING_UP;
    }
  else if (this->state == ::MoveUpDownTopArmor::State::MOVING_UP)
    {
      this->rLog.in.logMsg ("WARNING: received unexpected moveUp in MOVING_UP.");
    }
  else if (this->state == ::MoveUpDownTopArmor::State::MOVING_DOWN)
    {
      this->rLog.in.logMsg ("WARNING: received unexpected moveUp in MOVING_DOWN.");
    }
  else if (this->state == ::MoveUpDownTopArmor::State::DOWN)
    {
      this->r.in.moveUp ();
      this->state = ::MoveUpDownTopArmor::State::MOVING_UP;
    }
  else if (this->state == ::MoveUpDownTopArmor::State::UP)
    {
      this->rLog.in.logMsg ("WARNING: received unexpected moveUp in UP.");
    }
  else if (this->state == ::MoveUpDownTopArmor::State::ABORTING)
    {
      this->rLog.in.logMsg ("WARNING: received unexpected moveUp in ABORTING.");
    }
  else if (!(this->state == ::MoveUpDownTopArmor::State::ABORTING) && (!(this->state == ::MoveUpDownTopArmor::State::UP) && (!(this->state == ::MoveUpDownTopArmor::State::DOWN) && (!(this->state == ::MoveUpDownTopArmor::State::MOVING_DOWN) && (!(this->state == ::MoveUpDownTopArmor::State::MOVING_UP) && !(this->state == ::MoveUpDownTopArmor::State::IDLE)))))) this->dzn_locator.get<dzn::illegal_handler> ().handle (LOCATION);
  else this->dzn_locator.get<dzn::illegal_handler> ().handle (LOCATION);
}
void
MoveUpDownTopArmor::p_moveDown ()
{
  if (this->state == ::MoveUpDownTopArmor::State::IDLE)
    {
      this->r.in.moveDown ();
      this->state = ::MoveUpDownTopArmor::State::MOVING_DOWN;
    }
  else if (this->state == ::MoveUpDownTopArmor::State::MOVING_UP)
    {
      this->rLog.in.logMsg ("WARNING: received unexpected moveDown in MOVING_UP.");
    }
  else if (this->state == ::MoveUpDownTopArmor::State::MOVING_DOWN)
    {
      this->rLog.in.logMsg ("WARNING: received unexpected moveDown in MOVING_DOWN.");
    }
  else if (this->state == ::MoveUpDownTopArmor::State::DOWN)
    {
      this->rLog.in.logMsg ("WARNING: received unexpected moveDown in DOWN.");
    }
  else if (this->state == ::MoveUpDownTopArmor::State::UP)
    {
      this->r.in.moveDown ();
      this->state = ::MoveUpDownTopArmor::State::MOVING_DOWN;
    }
  else if (this->state == ::MoveUpDownTopArmor::State::ABORTING)
    {
      this->rLog.in.logMsg ("WARNING: received unexpected moveDown in ABORTING.");
    }
  else if (!(this->state == ::MoveUpDownTopArmor::State::ABORTING) && (!(this->state == ::MoveUpDownTopArmor::State::UP) && (!(this->state == ::MoveUpDownTopArmor::State::DOWN) && (!(this->state == ::MoveUpDownTopArmor::State::MOVING_DOWN) && (!(this->state == ::MoveUpDownTopArmor::State::MOVING_UP) && !(this->state == ::MoveUpDownTopArmor::State::IDLE)))))) this->dzn_locator.get<dzn::illegal_handler> ().handle (LOCATION);
  else this->dzn_locator.get<dzn::illegal_handler> ().handle (LOCATION);
}
void
MoveUpDownTopArmor::p_abort ()
{
  if (this->state == ::MoveUpDownTopArmor::State::IDLE)
    {
      this->r.in.abort ();
    }
  else if (this->state == ::MoveUpDownTopArmor::State::MOVING_UP)
    {
      this->r.in.abort ();
      this->state = ::MoveUpDownTopArmor::State::ABORTING;
    }
  else if (this->state == ::MoveUpDownTopArmor::State::MOVING_DOWN)
    {
      this->r.in.abort ();
      this->state = ::MoveUpDownTopArmor::State::ABORTING;
    }
  else if (this->state == ::MoveUpDownTopArmor::State::DOWN)
    {
      this->r.in.abort ();
    }
  else if (this->state == ::MoveUpDownTopArmor::State::UP)
    {
      this->r.in.abort ();
    }
  else if (this->state == ::MoveUpDownTopArmor::State::ABORTING)
    {
      this->rLog.in.logMsg ("WARNING: received unexpected abort in ABORTING.");
    }
  else if (!(this->state == ::MoveUpDownTopArmor::State::ABORTING) && (!(this->state == ::MoveUpDownTopArmor::State::UP) && (!(this->state == ::MoveUpDownTopArmor::State::DOWN) && (!(this->state == ::MoveUpDownTopArmor::State::MOVING_DOWN) && (!(this->state == ::MoveUpDownTopArmor::State::MOVING_UP) && !(this->state == ::MoveUpDownTopArmor::State::IDLE)))))) this->dzn_locator.get<dzn::illegal_handler> ().handle (LOCATION);
  else this->dzn_locator.get<dzn::illegal_handler> ().handle (LOCATION);
}
void
MoveUpDownTopArmor::r_moveFinished ()
{
  if (this->state == ::MoveUpDownTopArmor::State::MOVING_UP)
    {
      this->p.out.moveFinished ();
      this->state = ::MoveUpDownTopArmor::State::UP;
    }
  else if (this->state == ::MoveUpDownTopArmor::State::MOVING_DOWN)
    {
      this->p.out.moveFinished ();
      this->state = ::MoveUpDownTopArmor::State::DOWN;
    }
  else if (!(this->state == ::MoveUpDownTopArmor::State::MOVING_DOWN) && !(this->state == ::MoveUpDownTopArmor::State::MOVING_UP)) this->dzn_locator.get<dzn::illegal_handler> ().handle (LOCATION);
  else this->dzn_locator.get<dzn::illegal_handler> ().handle (LOCATION);
}
void
MoveUpDownTopArmor::r_moveAborted ()
{
  if (this->state == ::MoveUpDownTopArmor::State::ABORTING)
    {
      this->p.out.moveAborted ();
      this->state = ::MoveUpDownTopArmor::State::IDLE;
    }
  else if (!(this->state == ::MoveUpDownTopArmor::State::ABORTING)) this->dzn_locator.get<dzn::illegal_handler> ().handle (LOCATION);
  else this->dzn_locator.get<dzn::illegal_handler> ().handle (LOCATION);
}
void
MoveUpDownTopArmor::r_moveFailed ()
{
  if (this->state == ::MoveUpDownTopArmor::State::MOVING_UP)
    {
      this->p.out.moveFailed ();
      this->state = ::MoveUpDownTopArmor::State::IDLE;
    }
  else if (this->state == ::MoveUpDownTopArmor::State::MOVING_DOWN)
    {
      this->p.out.moveFailed ();
      this->state = ::MoveUpDownTopArmor::State::IDLE;
    }
  else if (!(this->state == ::MoveUpDownTopArmor::State::MOVING_DOWN) && !(this->state == ::MoveUpDownTopArmor::State::MOVING_UP)) this->dzn_locator.get<dzn::illegal_handler> ().handle (LOCATION);
  else this->dzn_locator.get<dzn::illegal_handler> ().handle (LOCATION);
}
// version 2.18.2
