// Generated by dzn code from MoveUpDownTopArmor.dzn
#include <dzn/runtime.hh>
namespace dzn
{
  struct locator;
  struct runtime;
}
#include <iostream>
#include <vector>
#include <map>
#include "IMoveUpDown.hh"
#include "IMoveUpDownRelaxed.hh"
#include "ILog.hh"
#ifndef MOVEUPDOWNTOPARMOR_HH
#define MOVEUPDOWNTOPARMOR_HH
#include "IMoveUpDownRelaxed.hh"
#include "IMoveUpDown.hh"
#include "ILog.hh"
struct MoveUpDownTopArmor: public dzn::component
{
  enum struct State
    {
      IDLE,MOVING_UP,UP,MOVING_DOWN,DOWN,ABORTING
    };
  dzn::meta dzn_meta;
  dzn::runtime& dzn_runtime;
  dzn::locator const& dzn_locator;
  ::MoveUpDownTopArmor::State state;
  std::function<void ()>* dzn_out_p;
  ::IMoveUpDownRelaxed p;
  ::IMoveUpDown r;
  ::ILog rLog;
  MoveUpDownTopArmor (dzn::locator const& locator);
  private:
  void p_moveUp ();
  void p_moveDown ();
  void p_abort ();
  void r_moveFinished ();
  void r_moveAborted ();
  void r_moveFailed ();
};
#endif // MOVEUPDOWNTOPARMOR_HH
// version 2.18.2
