// Generated by dzn code from MoveUpDown.dzn
#include <dzn/runtime.hh>
namespace dzn
{
  struct locator;
  struct runtime;
}
#include <iostream>
#include <vector>
#include <map>
#include "ITimer.hh"
#include "IMotor.hh"
#include "IDestinationSensor.hh"
#include "IPlanner.hh"
#include "IMoveUpDown.hh"
#include "IMoveUp.hh"
#include "IMoveDown.hh"
#ifndef MOVEUPDOWN_HH
#define MOVEUPDOWN_HH
#include "IMoveUpDown.hh"
#include "IMoveUp.hh"
#include "IMoveDown.hh"
struct MoveUpDown: public dzn::component
{
  enum struct State
    {
      IDLE,MOVING_UP,UP,MOVING_DOWN,DOWN,ABORTING
    };
  dzn::meta dzn_meta;
  dzn::runtime& dzn_runtime;
  dzn::locator const& dzn_locator;
  ::MoveUpDown::State state;
  std::function<void ()>* dzn_out_p;
  ::IMoveUpDown p;
  ::IMoveUp rUp;
  ::IMoveDown rDown;
  MoveUpDown (dzn::locator const& locator);
  private:
  void p_moveUp ();
  void p_moveDown ();
  void p_abort ();
  void rUp_moveFinished ();
  void rUp_moveAborted ();
  void rUp_moveFailed ();
  void rDown_moveFinished ();
  void rDown_moveAborted ();
  void rDown_moveFailed ();
};
#endif // MOVEUPDOWN_HH
// version 2.18.2
