// Generated by dzn code from StatefullMoveUp.dzn
#include <dzn/runtime.hh>
namespace dzn
{
  struct locator;
  struct runtime;
}
#include <iostream>
#include <vector>
#include <map>
#include "ITimer.hh"
#include "IMotor.hh"
#include "IDestinationSensor.hh"
#include "IPlanner.hh"
#include "IMoveUp.hh"
#ifndef SMOVEUP_HH
#define SMOVEUP_HH
#include "IMoveUp.hh"
struct SMoveUp: public dzn::component
{
  enum struct HomedState
    {
      NOT_HOMED,HOMED
    };
  enum struct MoveState
    {
      IDLE,MOVING,ABORTING
    };
  dzn::meta dzn_meta;
  dzn::runtime& dzn_runtime;
  dzn::locator const& dzn_locator;
  ::SMoveUp::HomedState homedState;
  ::SMoveUp::MoveState moveState;
  std::function<void ()>* dzn_out_p;
  ::IMoveUp p;
  ::IMoveUp homedMove;
  ::IMoveUp regularMove;
  SMoveUp (dzn::locator const& locator);
  private:
  void p_moveUp ();
  void p_abort ();
  void homedMove_moveFinished ();
  void homedMove_moveAborted ();
  void homedMove_moveFailed ();
  void regularMove_moveFinished ();
  void regularMove_moveAborted ();
  void regularMove_moveFailed ();
};
#endif // SMOVEUP_HH
// version 2.18.2
